---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Render Dockerfiles for custom images
      ansible.builtin.template:
        src: "{{ item.dockerfile }}"
        dest: "{{ molecule_ephemeral_directory }}/{{ item.name }}.Dockerfile"
        mode: "0644"
      loop: "{{ molecule_yml.platforms }}"
      when: item.dockerfile is defined

    - name: Build custom images when dockerfile is provided
      community.docker.docker_image:
        name: "{{ item.image }}"
        build:
          path: "{{ molecule_ephemeral_directory }}"
          dockerfile: "{{ item.name }}.Dockerfile"
        source: build
        force_source: true
      loop: "{{ molecule_yml.platforms }}"
      when: item.dockerfile is defined

    - name: Ensure test containers are running
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        command: sleep infinity
        privileged: "{{ 'nixos' in item.name }}"
        security_opts: "{{ ['seccomp=unconfined', 'apparmor=unconfined'] if 'nixos' in item.name else omit }}"
        recreate: true
        pull: "{{ False if 'nixos' in item.name else True }}"
      loop: "{{ molecule_yml.platforms }}"

    - name: Build instance config entries
      ansible.builtin.set_fact:
        instance_conf_dict: >-
          {{ instance_conf_dict | default([]) + [
            {
              'instance': item.name,
              'address': item.name,
              'user': 'root',
              'port': 22,
              'connection': 'docker',
              'identity_file': None,
              'ansible_ssh_common_args': "-o StrictHostKeyChecking=no"
            }
          ] }}
      loop: "{{ molecule_yml.platforms }}"

    - name: Convert instance config list
      ansible.builtin.set_fact:
        instance_conf: "{{ instance_conf_dict }}"

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
