---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Ensure test containers are running
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        command: sleep infinity
        pull: true
      loop: "{{ molecule_yml.platforms }}"

    - name: Build instance config entries
      ansible.builtin.set_fact:
        instance_conf_dict: >-
          {{ instance_conf_dict | default([]) + [
            {
              'instance': item.name,
              'address': item.name,
              'user': 'root',
              'port': 22,
              'connection': 'docker',
              'identity_file': None,
              'ansible_ssh_common_args': "-o StrictHostKeyChecking=no"
            }
          ] }}
      loop: "{{ molecule_yml.platforms }}"

    - name: Convert instance config list
      ansible.builtin.set_fact:
        instance_conf: "{{ instance_conf_dict }}"

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
