---
# Molecule configuration file.
# Dependency management (download roles/collections)
# Note: Keep YAML keys sorted alphabetically.
dependency:
  name: galaxy
  options:
    ignore-certs: false
    ignore-errors: false
    role-file: requirements.yml
    requirements-file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  molecule syntax
  ansible-lint
platforms:
  - name: alpine-latest
    image: i386/alpine:latest
  - name: debian-latest
    image: debian:latest
  - name: nixos-latest
    dockerfile: ../resources/playbooks/Dockerfile.j2
    image: cogni-ai-template-nixos:latest
    base_image: nixos/nix:latest
    pre_build_image: false
  - name: ubuntu-jammy
    image: ubuntu:jammy
  - name: ubuntu-noble
    image: ubuntu:noble
  - name: ubuntu-latest
    image: ubuntu:latest
provisioner:
  config_options:
    defaults:
      host_key_checking: false
      # Use the built-in default callback with result_format instead of community.general.yaml
      remote_tmp: /tmp/.ansible-tmp-$${USER}
      result_format: yaml
      stdout_callback: ansible.builtin.default
      verbosity: 1
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: auto_silent
    host_vars:
      nixos-latest:
        ansible_python_interpreter: /root/.nix-profile/bin/python3
  ssh_connection:
    pipelining: true
  name: ansible
  options:
    diff: true
    force-handlers: true
  playbooks:
    cleanup: cleanup.yml
    converge: converge.yml
    create: create.yml
    destroy: destroy.yml
    prepare: prepare.yml
    side_effect: side_effect.yml
    verify: verify.yml

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
