---
# @docs: <https://opencode.ai/docs>
name: Cogni AI Agent
concurrency:
  cancel-in-progress: true
  group: cogni-ai-agent-${{ github.event.issue.number || github.event.pull_request.number || github.ref }}
# yamllint disable-line rule:truthy
on:
  discussion:
    types:
      - created
      - edited
      - answered
  discussion_comment:
    types:
      - created
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
      - edited
  pull_request:
    types:
      - opened
      - edited
  pull_request_review_comment:
    types:
      - created
  workflow_call:
    inputs:
      model:  # @docs: <https://opencode.ai/zen/v1/models>
        description: Model to use for OpenCode
        required: true
        type: string
      prompt:
        description: Prompt for the agent
        required: true
        type: string
  workflow_dispatch:
    inputs:
      model:  # @docs: <https://opencode.ai/zen/v1/models>
        default: opencode/gemini-3-flash
        description: Model to use for OpenCode
        options:
          - opencode/big-pickle
          - opencode/claude-3-5-haiku
          - opencode/claude-haiku-4-5
          - opencode/claude-opus-4-5
          - opencode/claude-opus-4-6
          - opencode/claude-sonnet-4
          - opencode/claude-sonnet-4-5
          - opencode/claude-sonnet-4-6
          - opencode/gemini-3.1-pro
          - opencode/gemini-3-flash
          - opencode/glm-5
          - opencode/glm-5.1
          - opencode/gpt-5
          - opencode/gpt-5-codex
          - opencode/gpt-5-nano
          - opencode/gpt-5.3-codex
          - opencode/gpt-5.3-codex-spark
          - opencode/gpt-5.4
          - opencode/gpt-5.4-mini
          - opencode/gpt-5.4-nano
          - opencode/minimax-m2.5
          - opencode/minimax-m2.5-free
          - opencode/nemotron-3-super-free
          - opencode/qwen3-coder
          - opencode/qwen3.6-plus-free
        required: true
        type: choice
      prompt:
        description: Prompt for the agent
        required: true
        type: string

jobs:
  cogni-ai-agent:
    uses: Cogni-AI-OU/.github/.github/workflows/cogni-ai-agent.yml@main
    with:
      model: >-
        ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call')
        && inputs.model }}
      prompt: >-
        ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call')
        && inputs.prompt }}
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    secrets: inherit
